# -*- coding: utf-8 -*-
{
    'name': "Quick Ledger",
    'summary': """ Automated University Ledger Management Application """,
    'description': """Automated University Ledger Management Application""",
    'author': "Benny Katchy",
    'website': "http://www.quempssystems.com",
    'category': 'Uncategorized',
    'version': '1.0',
    'depends': ['base', 'board', 'mail', 'portal', 'backend_theme_v13'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/faculties_view.xml',
        'views/students_view.xml',
        'views/departments_view.xml',
        'views/courses_view.xml',
        'views/courses_entry_view.xml',
        'views/grades_view.xml',
        'views/grading_schemes_view.xml',
        'views/academic_diplomas_view.xml',
        'views/honours_view.xml',
        'views/honour_schemes_view.xml',
        'views/semesters_view.xml',
        'views/academic_levels_view.xml',
        'views/academic_programmes_view.xml',
        'views/academic_diploma_type_view.xml',
        'views/student_results_view.xml',
        'views/student_registrations_view.xml',
        "views/student_result_entry_view.xml",
        'views/school_courses_view.xml',
        'views/student_legacy_view.xml',
        'views/student_legacy_result_view.xml',
        'views/academic_years_view.xml',
        'views/entry_status_view.xml',
        'views/academic_position_view.xml',
        'views/academic_position_entry_view.xml',
        'views/lecturer_view.xml',
        'views/academic_fee_entries_view.xml',
        'views/academic_fees_view.xml',
        'views/academic_payment_entries_view.xml',
        'views/payment_types_view.xml',
        'views/student_ledgers_view.xml',
        'views/legacy_payment_view.xml',
        'wizard/academic_payment_wizard_view.xml',
        'wizard/ledger_entry_wizard_view.xml',
        'report/reports.xml',
        'report/student_ledger_report_template.xml',
        'report/student_ledger_detail_report_template.xml',
        'report/student_ledger_comprehensive_report_template.xml',
        'report/payment_entry_report_template.xml',
        'report/email_templates.xml',
        'report/ledger_entry_by_name_report_template.xml',
        'views/menu.xml'
    ],
    'demo': [
        'demo/demo.xml',
        'demo/arts_fees.xml',
        'demo/science_fees.xml'
    ],
    'images': [
        'static/description/logo.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
